### ISSUE TITLE
cannot run on macos 

### ISSUE THREAD

**Issue by flutter-painter** [VisualSystemsCorp/vsc_pdf_template_editor#36]
Hi,
Curious about how much pdf edition can be done using this lib.
While trying to run the template_editor/example on macos
VScode gives me : error runnning pod install

While xcode gives me :
Unable to load contents of file list: '...vsc_pdf_template_editor/vsc_pdf_template_editor/example/macos/Flutter/ephemeral/FlutterOutputs.xcfilelist'

**Comment by dsyrstad** [comment]
@flutter-painter I'm able to build successfully on macos using the latest from the `main` branch.

```
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
```

The example app is displayed when I run it, but has some issues loading http resources using the sample template. This is the first time I've built it for macos. We typically use it on web, android, and ios.

**Comment by flutter-painter** [comment]
OK, surely xcode 13 is to blame heure on m'y side, Thank you for checking, will upgrade somehow
